### ISSUE TITLE
Why doesen't this work?

### ISSUE THREAD

**Issue by ApertureDevelopment** [satom99/litcord#19]
I am trying to let my bot set the role of an user which wrote in a channel
I am doing this:
```
for k,v in pairs(server.members) do
		if not(k == "discriminator") then
			if v.id == userid then
				return v
			end
		end
		
	end
```

and it finds the right user, and returns it, but I can't use it somehow ...
How am I supposed to do this when i can't search in the tables for the right entry?

also your lib keeps getting an "invalid session" error

**Comment by satom99** [comment]
As stated on #17, litcord has been discontinued for quite a while now and thus is not to be used at its current state. You may find active and up-to-date libraries [here](https://discordapp.com/developers/docs/topics/libraries).

Either way, in case you still want to use litcord, you may instead loop using [ipairs](https://www.lua.org/pil/7.3.html) or do `server.members:get(userid)`. Keep in mind both this `get` method and your loop there do not return a member when there's no match for the given id.
