### ISSUE TITLE
Voice module not found

### ISSUE THREAD

**Issue by SinisterRectus** [satom99/litcord#3]
VoiceConnection.lua attempts to require voice module on line 8, but module does not exist in the lit release.

Tested on version 0.1.2

**Comment by satom99** [comment]
Voice is not finished and thus should not be used, hence current code may break at any point

**Comment by SinisterRectus** [comment]
I should have added that this happens when you require the main litcord module. The library code is attempting to access the non-existent voice module.

**Comment by satom99** [comment]
Issue solved, voice folder was not added to `package.lua` and so was not being pushed to _lit_. Still, voice is not functional though it contains latest testing modifications - useful in case anyone is willing to work on it further. Thanks for reporting.
